spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: none #create: 실행시점에 다 지우고 다시 생성
    properties:
      hibernate:
#        show-sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL : debug
